"""module settings and telegram users

Revision ID: ee9322807de8
Revises: 46a3fd08931a
Create Date: 2026-09-08 02:54:31.150341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee9322807de8'
down_revision: Union[str, None] = '46a3fd08931a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('module', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module', 'key', name='uq_module_setting')
    )
    op.create_index('ix_module_settings_module', 'module_settings', ['module'], unique=False)
    op.add_column('users', sa.Column('role', sa.String(length=16), nullable=False, server_default='member'))
    op.add_column('users', sa.Column('telegram_user_id', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('telegram_username', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_users_tg_user_id', 'users', ['telegram_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_tg_user_id', table_name='users')
    op.drop_column('users', 'last_seen_at')
    op.drop_column('users', 'telegram_username')
    op.drop_column('users', 'telegram_user_id')
    op.drop_column('users', 'role')
    op.drop_index('ix_module_settings_module', table_name='module_settings')
    op.drop_table('module_settings')
    # ### end Alembic commands ###